=== TukaWarrior/HFTM/XML/Zeiterfassung Beispiel von Simeon/zeiterfassung.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="super-ag.com/rapporte" 
    elementFormDefault="qualified"
    targetNamespace="super-ag.com/rapporte"
    xmlns:fin="super-ag.com/finance">
    <xs:import namespace="super-ag.com/finance" schemaLocation="finance.xsd"/>
    
    <xs:element name="rapport">
        <xs:complexType>
            <xs:all>
                <xs:element name="arbeitszeiten">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="eintrag" maxOccurs="unbounded"/>
                        </xs:sequence>      
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>


    <xs:element name="eintrag">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datum-von" type="xs:dateTime"/>
                <xs:element name="datum-bis" type="xs:dateTime"/>
                <xs:element name="taetigkeit" type="xs:string"/>
                <xs:element name="verrechenbar" type="xs:string"/>
                <xs:choice>
                    <xs:element ref="fin:projektnummer"/>
                    <xs:element ref="fin:kostenstelle"/>
                </xs:choice>    
            </xs:sequence>
            <xs:attribute name="ort">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="verrechenbarType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ja"/>
            <xs:enumeration value="Nein"/>
            <xs:enumeration value="Halb"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== TukaWarrior/HFTM/XML/Zeiterfassung Beispiel von Simeon/zeiterfassung.xml
<?xml version="1.0" encoding="UTF-8"?>
<rapport 
    xmlns="super-ag.com/rapporte"
    xmlns:gugus="https:/ /www.w3.org/2001/XMLSchema-instance" 
    gugus:schemaLocation="super-ag.com/rapporte zeiterfassung.xsd"
    xmlns:fin="super-ag.com/finance">
    <arbeitszeiten>
        <eintrag ort="">
            <datum-von>2023-09-05T13:45:00</datum-von>
            <datum-bis>2023-09-05T14:45:00</datum-bis>
            <taetigkeit>XSD Einf√ºhrung</taetigkeit>
            <verrechenbar>halb</verrechenbar>
            <fin:projektnummer>A123</fin:projektnummer>
        </eintrag>
    </arbeitszeiten>
</rapport>
