=== TukaWarrior/HFTM/XML/Praktikumsauftrag/Service-Rapport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="servicerapport">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="termin" type="xs:date" />
                <xs:element name="zeit" type="xs:time" />
                <xs:element ref="objekt" />
                <xs:element ref="kunde" />
                <xs:element ref="rechnung" />
                <xs:element ref="erteiltam" />
                <xs:element ref="erteiltvon" />
                <xs:element ref="auftrag" />
                <xs:element ref="bemerkung" />
                <xs:element ref="arbeitszeit" />
                <xs:element ref="material" />
                <xs:element ref="checkbox" />
                <xs:element ref="unterschrift" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="objekt">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="adresse" type="xs:String" />
                <xs:element name="ort" type="xs:String" />
                <xs:element name="telefonnummer" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="kunde">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="adresse" type="xs:String" />
                <xs:element name="ort" type="xs:String" />
                <xs:element name="telefonnummer" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="rechnung">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="adresse" type="xs:String" />
                <xs:element name="ort" type="xs:String" />
                <xs:element name="telefonnummer" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    </xs:element name="erteiltam" type="xs:Date"/>
    </xs:element name="erteiltvon" type="xs:string"/>

    </xs:element name="auftrag" type="xs:string"/>
    </xs:element name="bemerkung" type="xs:string"/>



    <xs:element name="arbeitszeit">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zeile" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                    <xs:element name="monteur" type="xs:string" />
                    <xs:element name="datum" type="xs:Date" />
                    <xs:element name="arbeitszeit" type="xs:double" />
                    <xs:element name="erledigtearbeit" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:complexType>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="checkbox">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="regie" type="xs:boolean"/>
                <xs:element name="garantie" type="xs:boolean" />
                <xs:element name="ausmass" type="xs:boolean" />
                <xs:element name="notfalleinsatz" type="xs:boolean" />
                <xs:element name="arbeitfertig" type="xs:boolean" />
            </xs:element>
        </xs:complexType>
    <checkbox>

    <xs:element name="material">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zeile" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="bezeichnung" type="xs:string" />
                            <xs:element name="em-nummer" type="xs:integer" />
                            <xs:element name="montageart" type="xs:string" />
                            <xs:element name="anzahl" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:complexType>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="unterschrift">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ort" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="datum" type="xs:Date" minOccurs="1" maxOccurs="1" />
                <xs:element name="unterschrift-kunde" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="unterschrift-monteur" type="xs:string" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TukaWarrior/HFTM/XML/Praktikumsauftrag/Service-Rapport.xml
<?xml version="1.0" encoding="UTF-8"?>
<servicerapport xmlns:xsi="http://www.w3.org/2001/XMLSchema"
    xsi:noNamespaceSchemaLocation="Service-Rapport.xsd">
    <termin>13.06.2023</termin>
    <zeit>13:00</zeit>

    <objekt> <!-- Objektadresse / Ausführungsadresse -->
        <name>Max Mustermann</name>
        <adresse>Musterstrasse 1</adresse>
        <ort>Musterhausen</ort>
        <telefonnummer>0629650001</telefonnummer>
    </objekt>
    <kunde> <!-- Kundenadresse -->
        <name>Beat Bàrtschi</name>
        <adresse>Buchenweg 2</adresse>
        <ort>Bern</ort>
        <telefonnummer>0629650002</telefonnummer>
    </kunde>
    <rechnung> <!-- Rechnungsadresse -->
        <name>Clemens</name>
        <adresse>Dorfstrasse 3</adresse>
        <ort>Bern</ort>
        <telefonnummer>0629650003</telefonnummer>
    </rechnung>

    <erteiltam>10.06.2023</erteiltam>
    <erteiltvon>Max Mustermann </erteiltvon>

    <auftrag>Steckdose defekt</auftrag>
    <bemerkungen>Kunde nicht zu hause. Schlüssel in Briefkasten.</bemerkungen>

    <arbeitszeit> <!-- Tabelle der benötigten Arbeitszeit -->
        <zeile>
            <monteur>Luca Bützberger</monteur>
            <datum>13.06.2023</datum>
            <arbeitszeit>3.0</arbeitszeit>
            <erledigtearbeit>Steckdose ausgewechselt</erledigtearbeit>
        </zeile>
    </arbeitszeit>

    <material> <!-- Tabelle des verbrauchten Materials -->
        <zeile>
            <bezeichnung>AP 3xT13 Feller</bezeichnung>
            <em-nummer>153256987</em-nummer>
            <montageart>A3</montageart>
            <anzahl>1</anzahl>
        </zeile>
    </material>

    <!-- Checkboxen zum ankreuzen -->
    <checkbox>
        <regie>false</regie>
        <garantie>false</garantie>
        <ausmass>true</ausmass>
        <notfalleinsatz>false</notfalleinsatz>
        <arbeitfertig>true</arbeitfertig>
    </checkbox>

    <!-- Unterschriften -->
    <unterschrift>
        <ort>Madiswil</ort>
        <datum>13.06.2023</datum>
        <unterschrift-kunde></unterschrift-kunde>
        <unterschrift-monteur></unterschrift-monteur>
    </unterschrift>
</servicerapport>
